In [1]:
import numpy as np

# N-dimensional array

In [2]:
x = np.array([[1,3],[2,4]])
x

array([[1, 3],
       [2, 4]])

In [3]:
x.ndim

2

In [4]:
x.shape

(2, 2)

In [5]:
x.dtype

dtype('int64')

In [6]:
np.info(x)

class:  ndarray
shape:  (2, 2)
strides:  (16, 8)
itemsize:  8
aligned:  True
contiguous:  True
fortran:  False
data pointer: 0x600003dd4000
byteorder:  little
byteswap:  False
type: int64


# Array creation

In [7]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.linspace(0, 10, num = 10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [9]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [10]:
np.diag([1,2,3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [11]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [12]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [13]:
np.empty((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [14]:
rng = np.random.default_rng(1076)
rng.random((3,2))

array([[0.36973526, 0.21850796],
       [0.84278736, 0.51110555],
       [0.71782768, 0.70735193]])

# Operations

In [15]:
x = rng.random((2,2))
y = rng.random((2,2))

x,y

(array([[0.38972569, 0.51182945],
        [0.30975595, 0.48354688]]),
 array([[0.17960314, 0.74440105],
        [0.62756887, 0.87047726]]))

In [16]:
x + 2 # 2 is broadcast into a ndarray of shape = (2,2)

array([[2.38972569, 2.51182945],
       [2.30975595, 2.48354688]])

In [17]:
x + y

array([[0.56932883, 1.25623049],
       [0.93732482, 1.35402414]])

In [18]:
x ** 2

array([[0.15188611, 0.26196938],
       [0.09594875, 0.23381759]])

In [19]:
2*x + 1

array([[1.77945137, 2.02365889],
       [1.6195119 , 1.96709376]])

In [20]:
x @ y # matrix multiplication

array([[0.39120419, 0.7356481 ],
       [0.35909211, 0.65149922]])

In [21]:
x.sum()

1.6948579607036631

In [22]:
x.min()

0.3097559497541028

In [23]:
x.max()

0.5118294450888611

In [24]:
x.argmax() # position of maximum element in flatten view

1

In [25]:
x.sum(axis = 0) # along x-axis (downward)

array([0.69948164, 0.99537633])

In [26]:
x.cumsum(axis = 1) # along y-axis (toward right)

array([[0.38972569, 0.90155513],
       [0.30975595, 0.79330283]])

# Universal function

`ufunc` are mathematical functions which applies to an ndarray elementwise

In [27]:
np.sin(x)

array([[0.37993469, 0.48977307],
       [0.30482621, 0.46492233]])

In [28]:
np.exp(x)

array([[1.47657569, 1.66834054],
       [1.36309241, 1.6218166 ]])

In [29]:
x

array([[0.38972569, 0.51182945],
       [0.30975595, 0.48354688]])

In [30]:
np.sort(x, axis = 0)

array([[0.30975595, 0.48354688],
       [0.38972569, 0.51182945]])

In [31]:
np.sort(x, axis = 1)

array([[0.38972569, 0.51182945],
       [0.30975595, 0.48354688]])

NOTE: there is no reverse sort in numpy instead use the below trick!

In [32]:
x

array([[0.38972569, 0.51182945],
       [0.30975595, 0.48354688]])

In [33]:
x[::-1,:]

array([[0.30975595, 0.48354688],
       [0.38972569, 0.51182945]])

In [34]:
np.sort(x, axis = 0)[::-1,:] # flip about the axis

array([[0.38972569, 0.51182945],
       [0.30975595, 0.48354688]])

In [35]:
np.inner(np.arange(1,3), np.arange(3,5)) # equivalent to np.sum(np.arange(1,3) * np.arange(3,5))

11

# Indexing

In [36]:
x

array([[0.38972569, 0.51182945],
       [0.30975595, 0.48354688]])

In [37]:
x.shape

(2, 2)

In [38]:
x.reshape(1,4) # returns a new ndarray

array([[0.38972569, 0.51182945, 0.30975595, 0.48354688]])

In [39]:
x.shape = 1,4

In [40]:
x

array([[0.38972569, 0.51182945, 0.30975595, 0.48354688]])

In [41]:
x.ndim

2

In [42]:
x[0,::2] # indexing each dimension using comma (,)

array([0.38972569, 0.30975595])

In [43]:
x > 0.5 # create boolean mask

array([[False,  True, False, False]])

In [44]:
x[x > 0.5]

array([0.51182945])

In [45]:
x = np.floor(10 * rng.random((2,2)))
x

array([[1., 6.],
       [0., 9.]])

In [46]:
x % 2 == 0

array([[False,  True],
       [ True, False]])

In [47]:
x[x % 2 == 0].size

2

# Shape manipulation

There are two main function when we want to add two or more arrays together
1. concatenate
2. stack

Main difference between `concatenate` and `stack` is that in stack we can create new dimension whereas in case of concatenate we can only add across existing dimension

In [48]:
x = np.floor(10 * rng.random((2,2)))
y = np.ceil(100 * rng.random((2,2)))

In [49]:
x

array([[6., 8.],
       [8., 3.]])

In [50]:
y

array([[78., 27.],
       [46., 91.]])

In [51]:
np.concatenate((x,y), axis = 0)

array([[ 6.,  8.],
       [ 8.,  3.],
       [78., 27.],
       [46., 91.]])

In [52]:
np.concatenate((x,y), axis = 1)

array([[ 6.,  8., 78., 27.],
       [ 8.,  3., 46., 91.]])

In [53]:
np.concatenate((x,y), axis = 2)

AxisError: axis 2 is out of bounds for array of dimension 2

In [54]:
np.stack((x,y), axis = 2) # whereas, stack along a new dimension is possible!

array([[[ 6., 78.],
        [ 8., 27.]],

       [[ 8., 46.],
        [ 3., 91.]]])

When it comes to splitting the ndarray we use the `np.split` function to split along a dimension

In [55]:
x

array([[6., 8.],
       [8., 3.]])

In [56]:
np.split(x, [1], axis = 0)

[array([[6., 8.]]), array([[8., 3.]])]

In [57]:
x1,x2 = np.split(x, [1], axis = 1) # split into two [:1] and [1:]

In [58]:
x1

array([[6.],
       [8.]])

In [59]:
# to squeeze the 2-dimension whose size = 1
x1.shape

(2, 1)

In [60]:
np.squeeze(x1, axis = 1)

array([6., 8.])

# Copy and views

By default, python always creates views to store memory and changes in a view affects the original variable. to avoid this we can create deep copy using `copy()`

In [61]:
x = np.sin(10 * rng.random((3,3)))

In [62]:
y = x

In [63]:
y is x

True

In [64]:
y

array([[-0.56991269,  0.50263336, -0.09107056],
       [-0.99866245, -0.1157579 , -0.73099497],
       [ 0.2130293 , -0.99810704, -0.92748036]])

In [65]:
y[0,:] = np.abs(y[0,:])

In [66]:
y

array([[ 0.56991269,  0.50263336,  0.09107056],
       [-0.99866245, -0.1157579 , -0.73099497],
       [ 0.2130293 , -0.99810704, -0.92748036]])

In [67]:
x

array([[ 0.56991269,  0.50263336,  0.09107056],
       [-0.99866245, -0.1157579 , -0.73099497],
       [ 0.2130293 , -0.99810704, -0.92748036]])